### ISSUE TITLE
Publish-AZWebApp Error

### ISSUE THREAD

**Issue by Vejitaxp** [gunnim/winget-restsource#1]
Hi,
first of all, thanks for the awesome Work.
I only got one Problem. The same one I got when I tried to create the Rest Source manually and I cant figure it out.
When I try to publish the WebApp it gets an Error.

`Publish-AzWebApp: C:\winget-restsource-master\WinGet.RestSource-Winget.PowerShell.Source\Library\New-ARMObjects.ps1:152
Line |
 152 |  …   $Result = Publish-AzWebApp -ArchivePath $RestSourcePath -ResourceGr …
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| One or more errors occurred. (A task was canceled.)`

It doesnt matter if I try it maually or your Script does it automatically.
Did you by anny chance encounter this Problem too?

**Comment by gunnim** [comment]
I got a lot of errors during script execution, what helped the most was starting with a fresh powershell and after failures executing
$Error

this allows you to examine the errors output by previous script executions and helped me immensely while troubleshooting.

A lot of what you might run into can be restrictions on resource names (name conflicts f.x. in azure) or limitations like the one cosmosdb in free tier per subscription.

HTH !

**Comment by Vejitaxp** [comment]
Yeah, i allready encounterd a lot of them in the last few weeks, trying it on and off.
I cant figure this one out, for the life of me.
It gives me nothing to work with...
Thanks for the quick answer

**Comment by gunnim** [comment]
Have you tried a different name for the resources you are creating and a fresh resource group ? A fresh setup on each iteration of changes often pushed me further

**Comment by gunnim** [comment]
It's also worth noting that Publish-AzWebApp is a standard Az cli command to publish contents to an azure app, if you are familiar with powershell debugging you could debug up to the point of that commands execution and replicate values in a separate shell session to tshoot further.

Or simply add output statements directly prior to execution of Publish-AzWebApp to see what's going into that command

**Comment by Vejitaxp** [comment]
> Have you tried a different name for the resources you are creating and a fresh resource group ? A fresh setup on each iteration of changes often pushed me further

Yes I have done that.



> It's also worth noting that Publish-AzWebApp is a standard Az cli command to publish contents to an azure app, if you are familiar with powershell debugging you could debug up to the point of that commands execution and replicate values in a separate shell session to tshoot further.
> 
> Or simply add output statements directly prior to execution of Publish-AzWebApp to see what's going into that command

I allready tried that one too.
But I will keep trying. Maybe I overlooked something.

**Comment by Vejitaxp** [comment]
FYI: I found the Issue after a lot of tinkering
Needed to add the Application Setting "WEBSITE_VNET_ROUTE_ALL" with Value 0.
That did the trick!
Thx anyway for your help! :)
